CREATE TABLE IF NOT EXISTS calculation_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    algorithm_type VARCHAR(255) NOT NULL,
    input_points_count INT NOT NULL,
    hull_points_count INT NOT NULL,
    calculation_time_ms DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);